version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install -g corepack@latest
      - corepack enable
      - corepack use pnpm@latest-10
      - pnpm install

  pre_build:
    commands:
      - echo "Generating Prisma client..."
      - pnpm prisma generate

  build:
    commands:
      - echo 'Building project...'
      - pnpm run build

artifacts:
  files:
    - 'dist/**/*'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - '.nvmrc'
    - 'prisma/**/*'
    - '.platform/**/*'
    - 'Procfile'
